# -*- coding: utf-8 -*-
#
# Copyright (C) 2020-2024 CERN.
# Copyright (C) 2020 Northwestern University.
#
# Invenio-RDM-Records is free software; you can redistribute it and/or modify
# it under the terms of the MIT License; see LICENSE file for more details.

name: CI

on:
  push:
    branches: master
  pull_request:
    branches:
      - master
      - "maint-**"
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 3 * * 6"
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason"
        required: false
        default: "Manual trigger"

jobs:
  Tests:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9, 3.12]
        db-service: [postgresql14]
        search-service: [opensearch2]
        node-version: [18.x, 20.x]
        include:
          - db-service: postgresql14
            DB_EXTRAS: "postgresql"

          - search-service: opensearch2
            SEARCH_EXTRAS: "opensearch2"

    env:
      DB: ${{ matrix.db-service }}
      SEARCH: ${{ matrix.search-service }}
      EXTRAS: tests,${{ matrix.SEARCH_EXTRAS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run eslint test
        run: ./run-js-linter.sh -i

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: setup.cfg

      - name: Install dependencies
        run: |
          pip install ".[$EXTRAS]"
          pip freeze
          docker --version
          docker-compose --version

      - name: Run translations test
        run: ./run-i18n-tests.sh

      - name: Run tests
        run: ./run-tests.sh

      - name: Install deps for frontend tests
        working-directory: ./invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records
        run: npm install

      - name: Install deps for frontend tests - translations
        working-directory: ./invenio_rdm_records/assets/semantic-ui/translations/invenio_rdm_records
        run: npm install

      - name: Run frontend tests
        working-directory: ./invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records
        run: npm test
